// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wibpxmtlsaqwtkkttrwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpYnB4bXRsc2Fxd3Rra3R0cndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTY0MDcsImV4cCI6MjA2OTQzMjQwN30.c9pi53CrSIlIiqXpMKnUtGw_ELMyddfyBMMrSYi9l14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});